# Generated by Django 5.2.15 on 2026-06-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('DELIVERED', 'Delivered')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
